fs = require('fs')
fs.writeFileSync('Lec1.txt', 'Json')
fs.appendFileSync('Lec1.txt', 'Node')
data = fs.readFileSync('Lec1.txt', 'utf-8')
console.log(data)
console.log('Process end')
fs.copyFileSync('Lec1.txt', 'Lec2.txt')
fs.renameSync('Lec1.txt', 'data.txt')
fs.unlinkSync('Lec2.txt')