var EventEmitter = require('events')
var ee = new EventEmitter()
fs = require('fs')
ee.on('work', () => {
    fs.mkdirSync('Test')
    fs.writeFileSync('Test/abc.txt', 'this is data')
    fs.appendFileSync('Test/abc.txt', '\nappended dATA')
    console.log("Data Appended Successfully")
    a = fs.readFileSync('Test/abc.txt', 'utf-8')
    fs.copyFileSync('Test/abc.txt', 'Test/pqr.txt')
    console.log(a)
    fs.unlinkSync('Test/abc.txt')
    console.log('All operations performed successfully')
})
ee.emit('work')